spring:
  application:
    name: Lobby server
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/lobby # Conf.
    username: be # Conf.
    password: secret # Conf.
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    validate-migration-naming: true
  web:
    resources:
      add-mappings: false

# logging.structured.format.console: ecs

management:
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8080 # Info
  servlet:
    context-path: /api/lobby # Conf.

springdoc:
  api-docs:
    enabled: true # Conf.
    path: /public/v3/api-docs
  swagger-ui:
    path: /public/docs # Conf. The path to the Swagger UI
    url: /public/v3/api-docs # Conf. The URL to the Swagger API docs
