spring:
  application:
    name: Lobby server
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/lobby # Conf.
    username: be # Conf.
    password: secret # Conf.
  jpa:
    open-in-view: false
  web:
    resources:
      add-mappings: false

server:
  port: 8080 # Info

springdoc:
  api-docs:
    enabled: true # Conf.
