apiVersion: v1
kind: Service
metadata:
  labels:
    app: lobby-service
  name: lobby-service
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: lobby-app
  type: ClusterIP